project:
  type: website
  output-dir: docs

website:
  title: "Marcin's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - portfolio.qmd
      - href: Marcin_Jaczynski_Resume.pdf
        text: CV

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    
    
    



